export type Theme = {
  breakPoint: {
    xSmallScreen: string,
    smallScreen: string,
    mediumScreen: string,
    largeScreen: string,
    extraLargeScreen: string,
  },
  shadow: {
    leftShadow: string,
    rightShadow: string,
    topShadow: string,
    bottomShadow: string,
  },
  spacing: {
    bigSpacing: string,
    regularSpacing: string,
    smallSpacing: string,
  },
  colors: {
    defaultColor: string,
    primaryColor: string,
    primaryDarkColor: string,
    primaryLightColor: string,
    secondaryColor: string,
    secondaryDarkColor: string,
    secondaryLightColor: string,
    primaryTextColor: string,
    secondaryTextColor: string,
    accentTextColor: string,
    accentColor: string,
    accentDarkOnly: string,
    borderColor: string,
    invert: number,
    defaultBackground: string,
    hyperLinkColor: string,
  }
};

export const LightTheme: Theme = {
  breakPoint: {
    xSmallScreen: 'max-width: 500px',
    smallScreen: 'max-width: 768px',
    mediumScreen: 'max-width: 1024px',
    largeScreen: 'max-width: 1280px',
    extraLargeScreen: 'max-width: 1400px',
  },
  shadow: {
    leftShadow: '-2px 0px 5px 0px #00000055',
    rightShadow: '2px 0px 5px 0px #00000055',
    topShadow: '0px 2px 5px 0px #00000055',
    bottomShadow: '0px -2px 5px 0px #00000055',
  },
  spacing: {
    bigSpacing: '2rem',
    regularSpacing: '1rem',
    smallSpacing: '0.5rem',
  },
  colors: {
    defaultColor: '#FFFFFF',
    primaryColor: '#2196F3',
    primaryDarkColor: '#1976D2',
    primaryLightColor: '#F5FAFF',
    secondaryColor: '#673AB7',
    secondaryDarkColor: '#512DA8',
    secondaryLightColor: '#D1C4E9',
    primaryTextColor: '#545454',
    secondaryTextColor: '#757575',
    accentTextColor: '#FFFFFF',
    accentColor: '#448AFF',
    accentDarkOnly: '#2196F3',
    borderColor: '#DDDDDD',
    invert: 0.25,
    defaultBackground: '#FFFFFF',
    hyperLinkColor: '#2196F3',
  },
};

export const DarkTheme: Theme = {
  breakPoint: {
    xSmallScreen: 'max-width: 500px',
    smallScreen: 'max-width: 768px',
    mediumScreen: 'max-width: 1024px',
    largeScreen: 'max-width: 1280px',
    extraLargeScreen: 'max-width: 1400px',
  },
  shadow: {
    leftShadow: '-2px 0px 5px 0px #00000055',
    rightShadow: '2px 0px 5px 0px #00000055',
    topShadow: '0px 2px 5px 0px #00000055',
    bottomShadow: '0px -2px 5px 0px #00000055',
  },
  spacing: {
    bigSpacing: '2rem',
    regularSpacing: '1rem',
    smallSpacing: '0.5rem',
  },
  colors: {
    defaultColor: '#1B1B1B',
    primaryColor: '#1B1B1B',
    primaryDarkColor: '#0A0A0A',
    primaryLightColor: '#1B1B1B',
    secondaryColor: '#673AB7',
    secondaryDarkColor: '#636363',
    secondaryLightColor: '#D2D2D2',
    primaryTextColor: '#FFFFFF',
    secondaryTextColor: '#B7B7B7',
    accentTextColor: '#FFFFFF',
    accentColor: '#BDCBFF',
    accentDarkOnly: '#EFEFEF',
    borderColor: '#4C4C4C',
    invert: 1,
    defaultBackground: '#252525;',
    hyperLinkColor: '#73baff',
  },
};
